# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 09:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_ext', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteext',
            name='site',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_ext', to='sites.Site'),
        ),
    ]
