# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-11 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_ext', '0002_auto_20170108_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteext',
            name='api_key',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
