# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-11 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_ext', '0003_siteext_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteext',
            name='callback_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='siteext',
            name='api_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
