# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-23 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_ext', '0005_remove_siteext_callback_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteext',
            name='callback_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
