# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 09:24
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('trashed', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Name')),
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, null=True)),
            ],
            options={
                'db_table': 'projects',
            },
        ),
    ]
