# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 09:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('trashed', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_btc', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('from_address', models.CharField(max_length=34, null=True)),
                ('to_address', models.CharField(max_length=34, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Unconfirmed'), (1, 'Partially Confirmed'), (2, 'Confirmed')], editable=False, null=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
                ('site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
            options={
                'db_table': 'transactions',
            },
        ),
    ]
