# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-01 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('trashed', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('hash', models.UUIDField(null=True)),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_btc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('receiving_address', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'transactions',
            },
        ),
    ]
