# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='receiving_address',
            new_name='to_address',
        ),
        migrations.AddField(
            model_name='transaction',
            name='project_code',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
