# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 10:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('payments', '0002_auto_20170108_1037'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together=set([('project', 'email')]),
        ),
    ]
