# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20170106_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='project_code',
            field=models.CharField(max_length=34, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='to_address',
            field=models.CharField(max_length=34, null=True),
        ),
    ]
