# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 09:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('payments', '0003_auto_20170106_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='hash',
        ),
        migrations.AddField(
            model_name='transaction',
            name='from_address',
            field=models.CharField(max_length=34, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.Site'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.IntegerField(choices=[(0, 'Unconfirmed'), (1, 'Partially Confirmed'), (2, 'Confirmed')], null=True),
        ),
    ]
