# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-11 01:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_remove_transaction_from_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount_btc',
            field=models.DecimalField(decimal_places=8, editable=False, max_digits=18, null=True),
        ),
    ]
