# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-11 12:39
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_auto_20170111_0148'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('trashed', models.BooleanField(default=False)),
                ('txid', models.CharField(max_length=255, null=True)),
                ('amount_paid', models.DecimalField(decimal_places=8, max_digits=18, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Unconfirmed'), (1, 'Partially Confirmed'), (2, 'Confirmed')], editable=False, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='amount_paid',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='txid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.Transaction'),
        ),
    ]
