# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_auto_20170107_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount_btc',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.IntegerField(choices=[(0, 'Unconfirmed'), (1, 'Partially Confirmed'), (2, 'Confirmed')], editable=False, null=True),
        ),
    ]
