# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-16 00:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('payments', '0005_auto_20170111_1239'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together=set([('project_code', 'email', 'site')]),
        ),
    ]
