# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-17 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_auto_20170116_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.IntegerField(choices=[(3, 'Initiated'), (0, 'Unconfirmed'), (1, 'Partially Confirmed'), (2, 'Confirmed')], editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.IntegerField(choices=[(3, 'Initiated'), (0, 'Unconfirmed'), (1, 'Partially Confirmed'), (2, 'Confirmed')], default=3, editable=False, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together=set([]),
        ),
    ]
