# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-20 01:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_transaction_webhook'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_emailed',
            field=models.BooleanField(default=False),
        ),
    ]
